### ISSUE TITLE
"pip install -e ."  failed, isn't there a "setup.py" in root dir?

### ISSUE THREAD

**Issue by chong-w** [adithya-s-k/omniparse#14]
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xw6cgkfo/flash-attn_66a00be6d8874e06ba191222d1bd5a0b/setup.py", line 9, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

**Comment by chenjunzeshen** [comment]
pip install packaging

**Comment by adithya-s-k** [comment]
As mentioned by @chenjunzeshen, `pip install packaging` should fix this issue.

Here is the code to install all the dependencies:
```
poetry install
# or
pip install -e .
# or
pip install -r pyproject.toml
```
