### ISSUE TITLE
what's wrong?no module named fastapi, python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by sdflysd** [adithya-s-k/omniparse#15]
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-xwfdbjmt\flash-attn_ef31244446e54cbfb62a9f56d8de18da\setup.py", line 9, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(omniparse-venv) E:\omniparse>python server.py --host 0.0.0.0 --port 8000 --documents --media --web
Traceback (most recent call last):
  File "E:\omniparse\server.py", line 3, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'

**Comment by chong-w** [comment]
+1

**Comment by adoresever** [comment]
+1

**Comment by CufeDigitalEcon** [comment]
and one
