### ISSUE TITLE
The code throws an error when running：python download.py --documents --media --web

### ISSUE THREAD

**Issue by OutBreak-hui** [adithya-s-k/omniparse#34]
Traceback (most recent call last):
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1560, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/transformers/models/mbart/modeling_mbart.py", line 53, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yq/omniparse/download.py", line 5, in <module>
    from omniparse import load_omnimodel
  File "/home/yq/omniparse/omniparse/__init__.py", line 27, in <module>
    from marker.models import load_all_models
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/marker/models.py", line 10, in <module>
    from surya.model.recognition.model import load_model as load_recognition_model
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/surya/model/recognition/model.py", line 14, in <module>
    from surya.model.recognition.decoder import MBartMoE
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/surya/model/recognition/decoder.py", line 4, in <module>
    from transformers import MBartForCausalLM, MBartConfig
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1551, in __getattr__
    value = getattr(module, name)
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1550, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1562, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.mbart.modeling_mbart because of the following error (look up to see its traceback):
/home/yq/anaconda3/envs/omniparse-venv/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

**Comment by chenyujie1127** [comment]
i met the same error！how to solve it correctly?

**Comment by xuanchengsunjin** [comment]
I also have the same problem,how to resolve it?
