### ISSUE TITLE
Error Failed to parse: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by AriesHaa** [adithya-s-k/omniparse#60]
![7a62cca7a17586839f4993e04aa2d4b](https://github.com/user-attachments/assets/27bcbce9-da09-47f4-9738-d1f4446865cf)
我的服务器目前已经启动了，但是解析不了任何文件，请问如何解决？如果能有人回答此问题，非常感谢！

**Comment by CyfZsj** [comment]
大佬请问您解决了吗？我在windows上用镜像启动没出现这个问题，但是在乌班图上用server.py启动也出现了这个问题

**Comment by AriesHaa** [comment]
> 大佬请问您解决了吗？我在windows上用镜像启动没出现这个问题，但是在乌班图上用server.py启动也出现了这个问题

抱歉，我也还在等待解决方法。如果有解决方法我会发到这里

**Comment by JeffRody** [comment]
same error, please feedback in English!

**Comment by JeffRody** [comment]
Traceback (most recent call last):
  File "E:\Anaconda3\envs\omniparse\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\Anaconda3\envs\omniparse\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api     
    output = await app.get_blocks().process_api(
  File "E:\Anaconda3\envs\omniparse\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "E:\Anaconda3\envs\omniparse\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\Anaconda3\envs\omniparse\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Anaconda3\envs\omniparse\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "E:\Anaconda3\envs\omniparse\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "E:\Anaconda3\envs\omniparse\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "F:\AiDocument\omniparse\omniparse\demo.py", line 219, in parse_document
    raise gr.Error(f"Failed to parse: {e}")
gradio.exceptions.Error: 'Failed to parse: Expecting value: line 1 column 1 (char 0)'
