### ISSUE TITLE
It there a way to run on a M Chip Mac ? 

### ISSUE THREAD

**Issue by unizhu** [adithya-s-k/omniparse#61]
I edit the Dockerfile and start to build the contaner , however , stuck on "flash-attn" which required CUDA installed.

```
Collecting flash-attn<3.0.0,>=2.6.1
6.344   Downloading flash_attn-2.6.1.tar.gz (2.6 MB)
6.606      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 10.1 MB/s eta 0:00:00
6.866   Preparing metadata (setup.py): started
7.576   Preparing metadata (setup.py): finished with status 'error'
7.578   error: subprocess-exited-with-error
7.578
7.578   × python setup.py egg_info did not run successfully.
7.578   │ exit code: 1
7.578   ╰─> [20 lines of output]
7.578       fatal: not a git repository (or any of the parent directories): .git
7.578       /tmp/pip-install-dstqun3y/flash-attn_b950b631e3d34687a63c814d66e390fe/setup.py:78: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
7.578         warnings.warn(
7.578       Traceback (most recent call last):
7.578         File "<string>", line 2, in <module>
7.578         File "<pip-setuptools-caller>", line 34, in <module>
7.578         File "/tmp/pip-install-dstqun3y/flash-attn_b950b631e3d34687a63c814d66e390fe/setup.py", line 134, in <module>
7.578           CUDAExtension(
7.578         File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1077, in CUDAExtension
7.578           library_dirs += library_paths(cuda=True)
7.578         File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1204, in library_paths
7.578           if (not os.path.exists(_join_cuda_home(lib_dir)) and
7.578         File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 2419, in _join_cuda_home
7.578           raise OSError('CUDA_HOME environment variable is not set. '
7.578       OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
7.578
7.578
7.578       torch.__version__  = 2.3.1
7.578
7.578
7.578       [end of output]
7.578
7.578   note: This error originates from a subprocess, and is likely not a problem with pip.
7.578 error: metadata-generation-failed
```

**Comment by adithya-s-k** [comment]
As i dont use a mac i cant develope for it👍🏼
