### ISSUE TITLE
【BUG】gradio.exceptions.Error:

### ISSUE THREAD

**Issue by Lu0Key** [adithya-s-k/omniparse#66]
```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/omniparse/demo.py", line 191, in parse_document
    response = requests.post(post_url, files=files, headers={"accept": "application/json"})
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=2867): Max retries exceeded with url: /parse_document (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc67cd498a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I use VSCode to remotely connect to a server. When I perform port forwarding through VSCode, I encounter an error when accessing localhost:2867. However, if I access the server using the public IP, it works fine. But I can't ensure that all users have a public IP and the permission to open port 8000.
GPT

The above content was translated using ChatGPT.

**Comment by JeffRody** [comment]
proxy
