### ISSUE TITLE
Run the Server: python server.py --host 0.0.0.0 --port 8002 --documents --media --web

### ISSUE THREAD

**Issue by xiaowei-1970290485** [adithya-s-k/omniparse#75]
Traceback (most recent call last):
  File "/tmp/pycharm_project_731/omniparse-main/server.py", line 6, in <module>
    from omniparse import load_omnimodel
  File "/tmp/pycharm_project_731/omniparse-main/omniparse/__init__.py", line 27, in <module>
    from marker.models import load_all_models
  File "/home/dtstack/miniconda3/envs/omniparse-venv/lib/python3.10/site-packages/marker/models.py", line 6, in <module>
    from surya.model.detection import segformer
ImportError: cannot import name 'segformer' from 'surya.model.detection' (unknown location)

**Comment by xiaowei-1970290485** [comment]
There is no effect on the output of the final result
