### ISSUE TITLE
[BUG] start failed on colab

### ISSUE THREAD

**Issue by thinking-and-coding** [adithya-s-k/omniparse#77]
The error messages are below:
`Traceback (most recent call last):
  File "/content/omniparse/server.py", line 62, in <module>
    main()
  File "/content/omniparse/server.py", line 48, in main
    load_omnimodel(args.documents, args.media, args.web)
  File "/content/omniparse/omniparse/__init__.py", line 58, in load_omnimodel
    shared_state.crawler = WebCrawler(verbose=True)
  File "/content/omniparse/omniparse/web/web_crawler.py", line 34, in __init__
    self.crawler_strategy = crawler_strategy or LocalSeleniumCrawlerStrategy(verbose=verbose)
  File "/content/omniparse/omniparse/web/crawler_strategy.py", line 94, in __init__
    self.driver = webdriver.Chrome(service=self.service, options=self.options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self._start_process(self._path)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 208, in _start_process
    self.process = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.wdm/drivers/chromedriver/linux64/127.0.6533.72/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver'`

it seem's like chromedriver format mismatch the platform?

**Comment by vane0912** [comment]
Hey i am getting the same issue, any advances on it yet? it was working for me before but now i get that same error

**Comment by Abdul37611** [comment]
I get this error only when I run the application with Docker, If I run it normally I'm not facing this issue

**Comment by thinking-and-coding** [comment]
I successfully ran it by just removing the '--web' parameter at startup ceil. However, this obviously doesn't resolve the problem. :(
<img width="693" alt="image" src="https://github.com/user-attachments/assets/4dfa4f20-ac5c-4a56-999f-e6cb45ef54f8">

**Comment by vane0912** [comment]
> I get this error only when I run the application with Docker, If I run it normally I'm not facing this issue

i have it when i run it with docker too not sure if maybe the latest chromedriver that is downloading is damaged or something because i previously didn't got the error

**Comment by reegan-anne** [comment]
Ultimately the fix for me was to update webdriver-manager package to v4.0.2
