### ISSUE TITLE
Using the Colab Notebook Gradio App fails

### ISSUE THREAD

**Issue by ivan-mihailov** [adithya-s-k/omniparse#9]
Very interesting project. Tried to spin it up from the Colab Notebook to compare the performance compared to commercial solutions but have been unable to get it to work at all. 

The app goes through the steps below then throws an error:

```
Detecting bboxes: 100% 10/10 [00:12<00:00,  1.21s/it]
Recognizing Text: 100% 60/60 [01:39<00:00,  1.66s/it]
Detecting bboxes: 100% 7/7 [00:12<00:00,  1.79s/it]
Finding reading order: 100% 7/7 [00:07<00:00,  1.09s/it]
```

**Here is the Traceback:**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/omniparse/omniparse/demo.py", line 193, in parse_document
    document_response = response.json()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 541, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 833, in wrapper
    response = f(*args, **kwargs)
  File "/content/omniparse/omniparse/demo.py", line 204, in parse_document
    raise gr.Error(f"Failed to parse: {e}")
gradio.exceptions.Error: 'Failed to parse: Expecting value: line 1 column 1 (char 0)'
```
Any help is appreciated!

**Comment by cnjack** [comment]
Same error

**Comment by adithya-s-k** [comment]
@ivan-mihailov @cnjack

It seems this issue might be caused by one of the internal modules not working properly, possibly due to the large size of the PDF file or another reason.

Could you please also try the /docs route and let us know if you encounter the same problem?

Additionally, could you share the size of the PDF you have uploaded? This information will help us troubleshoot the issue more effectively. Thank you!

**Comment by cnjack** [comment]
Do you mean open the /docs route in the browser? I can open it.
Or do you mean try with API directly?

**Comment by cnjack** [comment]
It works well when I try to run with the docker. and it still fail with the /docs endpoints.

**Comment by Krzemq** [comment]
I have the same error on Colab:
`INFO:     46.205.203.219:0 - "GET /queue/data?session_hash=b5vmo5wzvlq HTTP/1.1" 200 OK
Detecting bboxes: 100% 21/21 [00:16<00:00,  1.24it/s]
Recognizing Text: 100% 31/31 [00:47<00:00,  1.53s/it]
Detecting bboxes: 100% 14/14 [00:21<00:00,  1.50s/it]
Finding reading order: 100% 14/14 [00:14<00:00,  1.05s/it]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/omniparse/omniparse/demo.py", line 200, in parse_document
    document_response = response.json()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/content/omniparse/omniparse/demo.py", line 217, in parse_document
    raise gr.Error(f"Failed to parse: {e}")
gradio.exceptions.Error: 'Failed to parse: Expecting value: line 1 column 1 (char 0)'`

It's both for Documents (pdf - 16MB) or Media (mp4 - 200+MB).
