### ISSUE TITLE
python download.py  error

### ISSUE THREAD

**Issue by yxkj1515** [adithya-s-k/omniparse#93]
omniparse# python download.py --documents --media --web
/root/miniconda3/lib/python3.12/site-packages/pydantic/_internal/_fields.py:161: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

       .88888.                      oo  888888ba                                      
      d8'   `8b                         88    `8b                                     
      88     88 88d8b.d8b. 88d888b. dP a88aaaa8P' .d8888b. 88d888b. .d8888b. .d8888b. 
      88     88 88'`88'`88 88'  `88 88  88        88'  `88 88'  `88 Y8ooooo. 88ooood8 
      Y8.   .8P 88  88  88 88    88 88  88        88.  .88 88             88 88.  ... 
       `8888P'  dP  dP  dP dP    dP dP  dP        `88888P8 dP       `88888P' `88888P' 
                                                                                      
                                                                                      

Created by Adithya S K : https://twitter.com/adithya_s_k

[LOG] ✅ Loading OCR Model
Loaded detection model vikp/surya_det3 on device cuda with dtype torch.float16
Loaded detection model vikp/surya_layout3 on device cuda with dtype torch.float16
Loaded reading order model vikp/surya_order on device cuda with dtype torch.float16
Loaded recognition model vikp/surya_rec on device cuda with dtype torch.float16
/root/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Loaded texify model to cuda with torch.float16 dtype
/root/miniconda3/lib/python3.12/site-packages/transformers/models/auto/image_processing_auto.py:513: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
[LOG] ✅ Loading Vision Model
/root/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
[LOG] ✅ Loading Audio Model
[LOG] ✅ Loading Web Crawler
Traceback (most recent call last):
  File "/root/autodl-tmp/omniparse/download.py", line 23, in <module>
    download_models()
  File "/root/autodl-tmp/omniparse/download.py", line 19, in download_models
    load_omnimodel(args.documents, args.media, args.web)
  File "/root/autodl-tmp/omniparse/omniparse/__init__.py", line 64, in load_omnimodel
    shared_state.crawler = WebCrawler(verbose=True)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/omniparse/omniparse/web/web_crawler.py", line 39, in __init__
    self.crawler_strategy = crawler_strategy or LocalSeleniumCrawlerStrategy(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/omniparse/omniparse/web/crawler_strategy.py", line 97, in __init__
    self.driver = webdriver.Chrome(service=self.service, options=self.options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/root/miniconda3/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/root/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/root/miniconda3/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x5585ff0c24e3 <unknown>
#1 0x5585fedf1c76 <unknown>
#2 0x5585fee18757 <unknown>
#3 0x5585fee17029 <unknown>
#4 0x5585fee55ccc <unknown>
#5 0x5585fee5547f <unknown>
#6 0x5585fee4cde3 <unknown>
#7 0x5585fee222dd <unknown>
#8 0x5585fee2334e <unknown>
#9 0x5585ff0823e4 <unknown>
#10 0x5585ff0863d7 <unknown>
#11 0x5585ff090b20 <unknown>
#12 0x5585ff087023 <unknown>
#13 0x5585ff0551aa <unknown>
#14 0x5585ff0ab6b8 <unknown>
#15 0x5585ff0ab847 <unknown>
#16 0x5585ff0bb243 <unknown>
#17 0x7fcb35ad1ac3 <unknown>

**Comment by yuhp-zts** [comment]
Did you manage to solve this problem?
